config/routes.rb
Fridge::Application.routes.draw do

  resources :steps

  resources :projects do
    resources :features, :except => [:index] do
      resources :scenarios, :except => [:index, :show]
    end
  end

  root 'projects#index'

end

app/models/scenario.rb
class Scenario < ActiveRecord::Base
  belongs_to :feature
  has_many :steps
end

app/controllers/scenarios_controller.rb
class ScenariosController < ApplicationController
  before_action :set_scenario, only: [:show, :edit, :update, :destroy]

  # GET /scenarios/1
  # GET /scenarios/1.json
  def show
    @feature = @scenario.feature
    @project = @feature.project
  end

  # GET /scenarios/new
  def new
    @scenario = Scenario.new
    @feature = Feature.find(params[:feature_id])
    @project = Project.find(params[:project_id])
  end

  # GET /scenarios/1/edit
  def edit
  end

  # POST /scenarios
  # POST /scenarios.json
  def create
    @feature = Feature.find(params[:feature_id]) 
    @scenario = @feature.scenarios.create(scenario_params)
    @project = @feature.project

    respond_to do |format|
      if @scenario.save
        format.html { redirect_to project_feature_path(@project, @feature), notice: 'Scenario was successfully created.' }
        format.json { render action: 'show', status: :created, location: @scenario }
      else
        format.html { render action: 'new' }
        format.json { render json: @scenario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scenarios/1
  # PATCH/PUT /scenarios/1.json
  def update
    respond_to do |format|
      if @scenario.update(scenario_params)
        format.html { redirect_to @scenario, notice: 'Scenario was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @scenario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scenarios/1
  # DELETE /scenarios/1.json
  def destroy
    @scenario.destroy
    respond_to do |format|
      format.html { redirect_to scenarios_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_scenario
      @scenario = Scenario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def scenario_params
      params.require(:scenario).permit(:description, :background, :feature_id)
    end
end

app/helpers/scenarios_helper.rb
module ScenariosHelper
end

app/views/scenarios/_form.html.erb
<%= form_for([@project, @feature, @feature.scenarios.build]) do |f| %>
  <% if @scenario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@scenario.errors.count, "error") %> prohibited this scenario from being saved:</h2>

      <ul>
      <% @scenario.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :background %><br>
    <%= f.check_box :background %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/scenarios/edit.html.erb
<h1>Editing scenario</h1>

<%= render 'form' %>

<%= link_to 'Show', @scenario %> |
<%= link_to 'Back', scenarios_path %>

app/views/scenarios/index.html.erb
<h1>Listing scenarios</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Background</th>
      <th>Feature</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @scenarios.each do |scenario| %>
      <tr>
        <td><%= scenario.description %></td>
        <td><%= scenario.background %></td>
        <td><%= scenario.feature %></td>
        <td><%= link_to 'Show', scenario %></td>
        <td><%= link_to 'Edit', edit_scenario_path(scenario) %></td>
        <td><%= link_to 'Destroy', scenario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Scenario', new_scenario_path %>

app/views/scenarios/new.html.erb
<h1>New scenario</h1>

<%= render 'form' %>

<%= link_to 'Back', project_feature_path(@project, @feature) %>

app/views/scenarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @scenario.description %>
</p>

<p>
  <strong>Background:</strong>
  <%= @scenario.background %>
</p>

<p>
  <strong>Feature:</strong>
  <%= @scenario.feature.title %>
</p>

<table class="table">
  <thead>
    <td>ID</td>
    <td>Description</td>
  </thead>
  <tbody>
<% @scenario.steps.each do |step| %>
    <tr>
      <td><%= step.id %></td>
      <td><%= step.description %></td>
    </tr>
<% end %>
  </tbody>
</table>

<%= link_to 'Edit', edit_project_feature_scenario_path(@project, @feature, @scenario) %> |
<%= link_to 'Back', project_feature_path(@project, @feature) %>