config/routes.rb
Fridge::Application.routes.draw do

  resources :steps

  resources :projects do
    resources :features, :except => [:index] do
      resources :scenarios, :except => [:index, :show]
    end
  end

  root 'projects#index'

end

app/models/feature.rb
class Feature < ActiveRecord::Base
  belongs_to :project
  has_many :scenarios
end

app/controllers/features_controller.rb
class FeaturesController < ApplicationController
  before_action :set_feature, only: [:show, :edit, :update, :destroy]

  # GET /features/1
  # GET /features/1.json
  def show
    @project = @feature.project
  end

  # GET /features/new
  def new
    @feature = Feature.new
    @project = Project.find(params[:project_id])
  end

  # GET /features/1/edit
  def edit
  end

  # POST /features
  # POST /features.json
  def create
    @project = Project.find(params[:project_id])
    @feature = @project.features.create(feature_params)

    respond_to do |format|
      if @feature.save
        format.html { redirect_to project_path(@project), notice: 'Feature was successfully created.' }
        format.json { render action: 'show', status: :created, location: project_feature_path(@feature.project, @feature) }
      else
        format.html { render action: 'new' }
        format.json { render json: @feature.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /features/1
  # PATCH/PUT /features/1.json
  def update
    respond_to do |format|
      if @feature.update(feature_params)
        format.html { redirect_to @feature, notice: 'Feature was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @feature.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /features/1
  # DELETE /features/1.json
  def destroy
    @feature.destroy
    respond_to do |format|
      format.html { redirect_to features_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_feature
      @feature = Feature.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def feature_params
      params.require(:feature).permit(:title, :descripion, :project_id)
    end
end

app/helpers/features_helper.rb
module FeaturesHelper
end

app/views/features/_form.html.erb
<%= form_for([@project, @project.features.build]) do |f| %>
  <% if @feature.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@feature.errors.count, "error") %> prohibited this feature from being saved:</h2>

      <ul>
      <% @feature.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :descripion %><br>
    <%= f.text_area :descripion %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/features/edit.html.erb
<h1>Editing feature</h1>

<%= render 'form' %>

<%= link_to 'Show', @feature %> |
<%= link_to 'Back', features_path %>

app/views/features/index.html.erb
<h3><%= @features.first.project.title %></h3>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Descripion</th>
      <th>Project</th>
      <th>Actions</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @features.each do |feature| %>
      <tr>
        <td><%= feature.title %></td>
        <td><%= feature.descripion %></td>
        <td><%= feature.project.title %></td>
        <td><%= link_to 'Show', feature %></td>
        <td><%= link_to 'Edit', edit_feature_path(feature) %></td>
        <td><%= link_to 'Destroy', feature, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Feature', new_feature_path %>

app/views/features/new.html.erb
<h1>New feature</h1>

<%= render 'form' %>

<%= link_to 'Back', project_features_path(@project) %>

app/views/features/show.html.erb
<div class="row">
  <div class="col-md-12">
    <p id="notice"><%= notice %></p>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <h2><%= @feature.title %></h2>
    <p class="lead"><%= @feature.descripion %></p>
  </div>
</div>

<hr>

<% @feature.scenarios.each do |scen| %>
  <div class="row">
    <div class="col-md-12">
        <h3>Feature: <%= scen.description %></h3>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6 col-md-offset-1">
      <% scen.steps.each do |step| %>
        <p><%= step.description %></p>
      <% end %>
    </div>
  </div>
<% end %>

<hr>

<%= link_to 'New Scenario!', new_project_feature_scenario_path(@project, @feature) %> |
<%= link_to 'Edit', edit_project_feature_path(@project, @feature) %> |
<%= link_to 'Back', project_path(@project) %>